const LOCAL_KEY='wiring-local-v6';
const CABLES={
  utp4:{name:'UTP 4',colors:[['white-orange','Бело-оранжевый'],['orange','Оранжевый'],['white-green','Бело-зелёный'],['green','Зелёный'],['white-blue','Бело-синий'],['blue','Синий'],['white-brown','Бело-коричневый'],['brown','Коричневый']]},
  utp2:{name:'UTP2',colors:[['white-orange','Бело-оранжевый'],['orange','Оранжевый'],['white-blue','Бело-синий'],['blue','Синий']]},
  shvvp:{name:'ШВВП',colors:[['brown','Коричневый'],['blue','Синий']]},
  kspv:{name:'КСПВ',colors:[['brown','Коричневый'],['white','Белый']]}
};
const app=document.getElementById('app');
let devices=read(LOCAL_KEY)||[],currentId=null,editing=false;
function read(k){try{return JSON.parse(localStorage.getItem(k))}catch(e){return null}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function toast(t){const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
function cable(id){return CABLES[id]||null}
function colorFor(row){return cable(row.cableId)?.colors.find(x=>x[0]===row.colorId)}
function normalizeDevice(d){const legacy=d.cableId&&CABLES[d.cableId]?d.cableId:null;d.contacts=(Array.isArray(d.contacts)?d.contacts:[]).map(r=>({contact:r.contact||'',cableId:r.cableId||(legacy||''),colorId:r.colorId||''}));d.cableId='mixed';return d}
function normalizeAll(){devices=devices.map(normalizeDevice);write(LOCAL_KEY,devices)}
normalizeAll();
function deviceCableLabel(d){const ids=[...new Set(d.contacts.map(r=>r.cableId).filter(Boolean))];if(ids.length===1&&CABLES[ids[0]])return CABLES[ids[0]].name;if(ids.length>1)return 'Смешанное подключение';return 'Кабель не выбран'}
function homeScreen(){app.innerHTML=`<div class="header"><h1>Схемы расключения</h1></div>`+(devices.length?devices.map(d=>`<button class="device" data-id="${esc(d.id)}"><span class="icon">⌁</span><span class="deviceMain"><span class="name">${esc(d.name)}</span><span class="deviceCable">${esc(deviceCableLabel(d))}</span></span><span class="count">${d.contacts.length} контактов</span><span class="chev">›</span></button>`).join(''):`<div class="card empty"><div class="plug">🔌</div><h2>Пока ничего нет</h2><p class="muted">Добавьте устройство и для каждого контакта выберите свой кабель и жилу.</p></div>`)+`<button class="primary addDevice" id="addDevice">＋ Новое устройство</button>`;document.querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>{currentId=e.dataset.id;editing=false;render()});document.getElementById('addDevice').onclick=()=>{const name=prompt('Введите название устройства:');if(name?.trim()){const d={id:'local-'+uid(),name:name.trim(),cableId:'mixed',contacts:[]};devices.push(d);write(LOCAL_KEY,devices);currentId=d.id;editing=true;render()}}}
function cableOptions(selected=''){return `<option value="">Выберите кабель</option>`+Object.entries(CABLES).map(([id,c])=>`<option value="${id}" ${id===selected?'selected':''}>${esc(c.name)}</option>`).join('')}
function colorOptions(row){const c=cable(row.cableId);return `<option value="">Выберите жилу</option>`+(c?c.colors.map(x=>`<option value="${x[0]}" ${x[0]===row.colorId?'selected':''}>${esc(x[1])}</option>`).join(''):'')}
function wireSwatch(row){const c=colorFor(row);return `<span class="wireSwatch ${esc(c?.[0]||'empty')}"></span>`}
function contactViewRow(r){const c=colorFor(r),cableName=cable(r.cableId)?.name||'Кабель не выбран',colorName=c?.[1]||'Жила не выбрана';return `<div class="viewRow"><div class="viewContact">${esc(r.contact||'Без названия')}</div><div class="viewWire"><div class="viewCable">${esc(cableName)}</div><div class="viewColor">${wireSwatch(r)}<span>${esc(colorName)}</span></div></div></div>`}
function contactRow(r,i){return `<div class="row"><div class="contactField"><label>Контакт</label><input class="contact" data-i="${i}" value="${esc(r.contact)}" placeholder="Например: GND"></div><div class="wireFields"><div><label>Кабель</label><select class="cableSelect" data-i="${i}">${cableOptions(r.cableId)}</select></div><div><label>Цвет жилы</label><span class="editorWireSwatch ${esc(r.colorId||'empty')}"></span><select class="colorSelect" data-i="${i}" ${r.cableId?'':'disabled'}>${colorOptions(r)}</select></div></div><div class="rowButtons"><button class="del" data-i="${i}">×</button></div></div>`}
function wirePaint(){document.querySelectorAll('.editorWireSwatch').forEach(w=>{w.className='editorWireSwatch '+(w.parentElement.querySelector('.colorSelect')?.value||'empty')})}
function persist(){write(LOCAL_KEY,devices)}
function bindEditor(d){document.querySelectorAll('.contact').forEach(e=>e.oninput=()=>{d.contacts[+e.dataset.i].contact=e.value;persist()});document.querySelectorAll('.cableSelect').forEach(e=>e.onchange=()=>{const r=d.contacts[+e.dataset.i];r.cableId=e.value;r.colorId='';persist();render()});document.querySelectorAll('.colorSelect').forEach(e=>e.onchange=()=>{d.contacts[+e.dataset.i].colorId=e.value;persist();wirePaint()});document.querySelectorAll('.del').forEach(e=>e.onclick=()=>{d.contacts.splice(+e.dataset.i,1);persist();render()});document.getElementById('addContact').onclick=()=>{d.contacts.push({contact:'',cableId:'',colorId:''});persist();render()};wirePaint()}
function removeDevice(d){if(!confirm('Удалить устройство и его схему?'))return;devices=devices.filter(x=>x!==d);persist();currentId=null;editing=false;toast('Удалено');render()}
function renameDevice(d){const n=prompt('Новое название:',d.name);if(n?.trim()){d.name=n.trim();persist();render()}}
function editorScreen(){const d=devices.find(x=>x.id===currentId);if(!d){currentId=null;return render()}normalizeDevice(d);if(!editing){app.innerHTML=`<div class="header"><button class="back" id="back">‹</button><div class="titleBlock"><h1>${esc(d.name)}</h1></div></div><div class="actions"><button class="secondary" id="rename">✎ Переименовать</button><button class="danger" id="remove">Удалить</button></div><div class="card"><div class="sectionHead"><b>Расключение</b></div>${d.contacts.length?d.contacts.map(contactViewRow).join(''):`<div class="empty small"><span class="muted">Контактов пока нет.</span></div>`}</div><button class="primary" id="edit" style="display:block;width:100%;max-width:980px;margin:16px auto 0;font-size:20px">✎ Редактировать</button>`;document.getElementById('back').onclick=()=>{currentId=null;render()};document.getElementById('edit').onclick=()=>{editing=true;render()};document.getElementById('rename').onclick=()=>renameDevice(d);document.getElementById('remove').onclick=()=>removeDevice(d);return}
app.innerHTML=`<div class="header"><button class="back" id="back">‹</button><div class="titleBlock"><h1>${esc(d.name)}</h1><span class="titleCable">Редактирование</span></div></div><div class="actions"><button class="secondary" id="rename">✎ Переименовать</button><button class="danger" id="remove">Удалить</button></div><div class="card"><div class="sectionHead"><b>Расключение</b><div class="muted subtitle">Для каждого контакта — свой кабель и цвет жилы</div></div>${d.contacts.length?d.contacts.map(contactRow).join(''):`<div class="empty small"><span class="muted">Контактов пока нет.</span></div>`}<button class="secondary add" id="addContact">＋ Добавить контакт</button></div><button class="primary" id="done" style="display:block;width:100%;max-width:980px;margin:16px auto 0;font-size:20px">✓ Готово</button>`;document.getElementById('back').onclick=()=>{editing=false;render()};document.getElementById('done').onclick=()=>{editing=false;persist();toast('Сохранено');render()};document.getElementById('rename').onclick=()=>renameDevice(d);document.getElementById('remove').onclick=()=>removeDevice(d);bindEditor(d)}
function render(){if(currentId)editorScreen();else homeScreen()}
window.addEventListener('load',render);
if('serviceWorker' in navigator){addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
